//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
// 
namespace TemplateBuilder.Wpf.CommandDefinitions {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/BlueStacksScriptGeneratorFGO/CommandDefinitions.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/BlueStacksScriptGeneratorFGO/CommandDefinitions.xsd", IsNullable=false)]
    public partial class CommandDefinitions {
        
        private CommandDefinitionsCommandGroup[] commandsField;
        
        private CommandDefinitionsModifierGroup[] modifierDefinitionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CommandGroup", IsNullable=false)]
        public CommandDefinitionsCommandGroup[] Commands {
            get {
                return this.commandsField;
            }
            set {
                this.commandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ModifierGroup", IsNullable=false)]
        public CommandDefinitionsModifierGroup[] ModifierDefinitions {
            get {
                return this.modifierDefinitionsField;
            }
            set {
                this.modifierDefinitionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/BlueStacksScriptGeneratorFGO/CommandDefinitions.xsd")]
    public partial class CommandDefinitionsCommandGroup {
        
        private CommandDefinitionsCommandGroupCommand[] itemsField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Command")]
        public CommandDefinitionsCommandGroupCommand[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/BlueStacksScriptGeneratorFGO/CommandDefinitions.xsd")]
    public partial class CommandDefinitionsCommandGroupCommand {
        
        private string contentField;
        
        private CommandDefinitionsCommandGroupCommandModifier[] modifiersField;
        
        private string titleField;
        
        private string commandField;
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Modifier", IsNullable=false)]
        public CommandDefinitionsCommandGroupCommandModifier[] Modifiers {
            get {
                return this.modifiersField;
            }
            set {
                this.modifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/BlueStacksScriptGeneratorFGO/CommandDefinitions.xsd")]
    public partial class CommandDefinitionsCommandGroupCommandModifier {
        
        private string groupField;
        
        private string replaceWithOverrideField;
        
        private string defaultArgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string replaceWithOverride {
            get {
                return this.replaceWithOverrideField;
            }
            set {
                this.replaceWithOverrideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string defaultArg {
            get {
                return this.defaultArgField;
            }
            set {
                this.defaultArgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/BlueStacksScriptGeneratorFGO/CommandDefinitions.xsd")]
    public partial class CommandDefinitionsModifierGroup {
        
        private CommandDefinitionsModifierGroupModifierDefinition[] itemsField;
        
        private string repleceWithField;
        
        private string keyField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ModifierDefinition")]
        public CommandDefinitionsModifierGroupModifierDefinition[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string repleceWith {
            get {
                return this.repleceWithField;
            }
            set {
                this.repleceWithField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/BlueStacksScriptGeneratorFGO/CommandDefinitions.xsd")]
    public partial class CommandDefinitionsModifierGroupModifierDefinition {
        
        private string titleField;
        
        private string argField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arg {
            get {
                return this.argField;
            }
            set {
                this.argField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
